### ISSUE TITLE
Whenever we try to bulk update the names of the games, the extension don't do anything

### ISSUE THREAD

**Issue by ferrazpedro** [polson/screenscraper-playnite-metadata-plugin#6]
Hey! I've been testing some things and noticed that when the name of the game is chosen to be updated in bulk tagging, it never works. 

I've tried to debug this but still don't understand what's happening, since Crow's extensions works fine and this also works when tagging only one game.

**Comment by polson** [comment]
I think this is a playnite bug, see here:
https://github.com/JosefNemec/Playnite/issues/2482#issuecomment-1080024554

And here:
https://github.com/JosefNemec/Playnite/issues/2482#issuecomment-1080028194

**Comment by ferrazpedro** [comment]
Since Crow already fixed this in Playnite, i'm closing this issue. Thanks a lot for giving him such detailed info!
