### ISSUE TITLE
Unable to Scrape Titles recently

### ISSUE THREAD

**Issue by chefreinhold** [polson/screenscraper-playnite-metadata-plugin#8]
Hi,
I have not been able to scrape games recently using this extension. I get an error message that says "Object reference not set to an instance of an object"

I have attached a copy of the logs here

Playnite log: https://pastebin.pl/view/364fab32

**Comment by polson** [comment]
Hi, 

It seems to be working for me currently.  Are you still having issues?

**Comment by polson** [comment]
Have created an account on [screenscraper.fr](https://screenscraper.fr/) and added your login credentials in the plugin settings?

**Comment by polson** [comment]
I did find some issues, should be fixed here: https://github.com/polson/screenscraper-playnite-metadata-plugin/pull/10
